// <auto-generated />
using Crossword.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Crossword.Migrations
{
    [DbContext(typeof(CrosswordDbContext))]
    [Migration("20251006173920_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Crossword.Models.Field", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<string>("Guesses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Squares")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Fields");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Completed = false,
                            Guesses = "[\"\\u0160\"]",
                            Squares = "[{\"Item1\":9,\"Item2\":6},{\"Item1\":10,\"Item2\":6},{\"Item1\":11,\"Item2\":6},{\"Item1\":12,\"Item2\":6}]"
                        });
                });

            modelBuilder.Entity("Crossword.Models.Word", b =>
                {
                    b.Property<string>("strword")
                        .HasColumnType("text");

                    b.HasKey("strword");

                    b.ToTable("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
