CREATE TABLE IF NOT EXISTS kompanija
(
    pavadinimas 		VARCHAR(64) 				PRIMARY KEY CHECK (pavadinimas ~ '^[A-Z]'), /* Pirma raidė didžioji */
    limitas_kg 			DECIMAL(9,1) 	NOT NULL 				CHECK (limitas_kg > 0),
    eur_uz_kg 			DECIMAL(9,2) 	NOT NULL 				CHECK (eur_uz_kg > 0)
);

CREATE TABLE IF NOT EXISTS paketas
(
	id 					INT 						GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	kilmes_salis 		VARCHAR(2)								DEFAULT 'XX', /* Šalies kodas - ISO 3166-1  */
	galutinis_tikslas 	VARCHAR(64) 	NOT NULL,
	data_sukurta 		DATE 			NOT NULL				DEFAULT NOW(),
	kompanija 			VARCHAR(64) 	NOT NULL 	REFERENCES kompanija(pavadinimas) 
);

CREATE TABLE IF NOT EXISTS galutine_busena
(
	paketo_id 			INT 						PRIMARY KEY REFERENCES paketas(id),
	data_pristatyta 	TIMESTAMP 		NOT NULL				DEFAULT NOW(),
	busena 				INT 			NOT NULL 				CHECK (busena IN (1, 2, 3, 4, 5))
);

CREATE TABLE IF NOT EXISTS zingsnis
(
	id 					INT 						GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	paketo_id 			INT 			NOT NULL	REFERENCES paketas(id),
	tikslas_is 			VARCHAR(64) 	NOT NULL,
	tikslas_i 			VARCHAR(64) 	NOT NULL,
	busena 				VARCHAR(64) 	NOT NULL,
	ivykdymo_data 		DATE
);

CREATE TABLE IF NOT EXISTS preke
(
	id 					INT 						GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	pavadinimas 		VARCHAR(64) 	NOT NULL,
    kaina_eur 			DECIMAL(9,2) 	NOT NULL 				CHECK (kaina_eur > 0),
    svoris_kg 			DECIMAL(9,1) 	NOT NULL 				CHECK (svoris_kg > 0)
);

CREATE TABLE IF NOT EXISTS paketo_preke
(
	paketo_id 			INT 						REFERENCES paketas(id),
	prekes_id 			INT 						REFERENCES preke(id),
													PRIMARY KEY (paketo_id, prekes_id),
	kiekis 				INT 			NOT NULL				CHECK (kiekis > 0)
);

CREATE OR REPLACE VIEW paketo_svoris AS
	SELECT pp.paketo_id, SUM(p.svoris_kg * pp.kiekis) AS visas_svoris
		FROM paketo_preke pp
		JOIN preke p ON p.id = pp.prekes_id
		GROUP BY pp.paketo_id
		ORDER BY pp.paketo_id
;

CREATE OR REPLACE VIEW siuntimo_kaina AS
	SELECT p.id, TRUNC(k.eur_uz_kg * s.visas_svoris, 2) AS siuntimo_kaina
		FROM paketo_svoris s
		JOIN paketas p ON p.id = s.paketo_id
		JOIN kompanija k ON p.kompanija = k.pavadinimas
;

DROP MATERIALIZED VIEW IF EXISTS pristatyti_paketai;
CREATE MATERIALIZED VIEW pristatyti_paketai AS
	SELECT paketo_id, data_pristatyta
	FROM galutine_busena g 
	JOIN paketas p ON p.id = g.paketo_id
;

CREATE INDEX IF NOT EXISTS zingsniai_pagal_busena
	ON zingsnis(busena)
	INCLUDE (id)
;

CREATE UNIQUE INDEX IF NOT EXISTS prekes
	ON paketo_preke(paketo_id, prekes_id)
;

