CREATE TABLE IF NOT EXISTS kompanija
(
    pavadinimas 		VARCHAR(64) 				PRIMARY KEY CHECK (pavadinimas ~ '^[A-Z]'), /* Pirma raidė didžioji */
    limitas_kg 			DECIMAL(9,1) 	NOT NULL 				CHECK (limitas_kg > 0),
    eur_uz_kg 			DECIMAL(9,2) 	NOT NULL 				CHECK (eur_uz_kg > 0)
);

CREATE TABLE IF NOT EXISTS paketas
(
	id 					INT 						GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	kilmes_salis 		VARCHAR(2)								DEFAULT 'XX', /* Šalies kodas - ISO 3166-1  */
	galutinis_tikslas 	VARCHAR(64) 	NOT NULL,
	data_sukurta 		DATE 			NOT NULL				DEFAULT NOW(),
	kompanija 			VARCHAR(64) 	NOT NULL 	REFERENCES kompanija(pavadinimas) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS galutine_busena
(
	paketo_id 			INT 						PRIMARY KEY REFERENCES paketas(id) ON DELETE CASCADE,
	data_pristatyta 	TIMESTAMP 		NOT NULL				DEFAULT NOW(),
	busena 				INT										CHECK (busena IN (1, 2, 3, 4, 5))
);

CREATE TABLE IF NOT EXISTS zingsnis
(
	id 					INT 						GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	paketo_id 			INT 			NOT NULL	REFERENCES paketas(id) ON DELETE CASCADE,
	tikslas_is 			VARCHAR(64) 	NOT NULL,
	tikslas_i 			VARCHAR(64) 	NOT NULL,
	busena 				VARCHAR(64) 	NOT NULL,
	ivykdymo_data 		DATE
);

CREATE TABLE IF NOT EXISTS preke
(
	id 					INT 						GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	pavadinimas 		VARCHAR(64) 	NOT NULL,
    kaina_eur 			DECIMAL(9,2) 	NOT NULL 				CHECK (kaina_eur > 0),
    svoris_kg 			DECIMAL(9,1) 	NOT NULL 				CHECK (svoris_kg > 0)
);

CREATE TABLE IF NOT EXISTS paketo_preke
(
	paketo_id 			INT 						REFERENCES paketas(id)  ON DELETE CASCADE,
	prekes_id 			INT 						REFERENCES preke(id)    ON DELETE CASCADE,
													PRIMARY KEY (paketo_id, prekes_id),
	kiekis 				INT 			NOT NULL				CHECK (kiekis > 0)
);

CREATE OR REPLACE VIEW paketo_svoris AS
	SELECT pp.paketo_id, SUM(p.svoris_kg * pp.kiekis) AS visas_svoris
		FROM paketo_preke pp
		JOIN preke p ON p.id = pp.prekes_id
		GROUP BY pp.paketo_id
		ORDER BY pp.paketo_id
;

CREATE OR REPLACE VIEW siuntimo_kaina AS
	SELECT p.id, TRUNC(k.eur_uz_kg * s.visas_svoris, 2) AS siuntimo_kaina
		FROM paketo_svoris s
		JOIN paketas p ON p.id = s.paketo_id
		JOIN kompanija k ON p.kompanija = k.pavadinimas
;

DROP MATERIALIZED VIEW IF EXISTS paketu_ataskaita;
CREATE MATERIALIZED VIEW paketu_ataskaita AS
SELECT 
    p.id AS paketo_id,
    p.galutinis_tikslas,
    g.data_pristatyta,
    k.pavadinimas AS kompanija,
    k.eur_uz_kg,
    COALESCE(ps.visas_svoris, 0) AS paketo_svoris,
    ROUND(COALESCE(ps.visas_svoris, 0) * k.eur_uz_kg, 2) AS siuntimo_kaina,

    (
        SELECT COUNT(*) 
        FROM zingsnis z
        WHERE z.paketo_id = p.id AND z.ivykdymo_data IS NOT NULL
    ) AS atliktu_zingsniu_skaicius

	FROM galutine_busena g
	JOIN paketas p ON p.id = g.paketo_id
	JOIN kompanija k ON k.pavadinimas = p.kompanija
	LEFT JOIN paketo_svoris ps ON ps.paketo_id = p.id
;


CREATE INDEX IF NOT EXISTS zingsniai_pagal_busena
	ON zingsnis(busena)
	INCLUDE (id)
;

CREATE UNIQUE INDEX IF NOT EXISTS prekes
	ON paketo_preke(paketo_id, prekes_id)
;


CREATE OR REPLACE FUNCTION tikrinti_paketu_svori()
RETURNS TRIGGER AS $$
DECLARE
    dabartinis_svoris DECIMAL(9,1);
    visas_svoris DECIMAL(9,1);
    kompanijos_limitas DECIMAL(9,1);
    prekes_svoris_kg DECIMAL(9,1);
BEGIN
    -- viso paketo svoris be naujos prekės
    SELECT COALESCE(SUM(p.svoris_kg * pp.kiekis), 0)
    INTO dabartinis_svoris
    FROM paketo_preke pp
    JOIN preke p ON p.id = pp.prekes_id
    WHERE pp.paketo_id = NEW.paketo_id;

    -- naujos prekės svoris
    SELECT svoris_kg INTO prekes_svoris_kg FROM preke WHERE id = NEW.prekes_id;

    visas_svoris := dabartinis_svoris + (prekes_svoris_kg * NEW.kiekis);

    -- kompanijos limitas
    SELECT k.limitas_kg
    INTO kompanijos_limitas
    FROM kompanija k
    JOIN paketas pk ON pk.kompanija = k.pavadinimas
    WHERE pk.id = NEW.paketo_id;

    IF visas_svoris > kompanijos_limitas THEN
        RAISE EXCEPTION 'Klaida: Paketo svoris (% kg) negali būti didesnis nei kompanijos limitas (% kg)', visas_svoris, kompanijos_limitas;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS paketu_svorio_limitu_patikra ON paketo_preke;

CREATE TRIGGER paketu_svorio_limitu_patikra
BEFORE INSERT OR UPDATE ON paketo_preke
FOR EACH ROW EXECUTE FUNCTION tikrinti_paketu_svori();



CREATE OR REPLACE FUNCTION insertinti_galutine_besena()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.ivykdymo_data IS NOT NULL 
		AND NEW.tikslas_i = (
			SELECT galutinis_tikslas
				FROM paketas 
				WHERE id = NEW.paketo_id
				) 
		AND NOT EXISTS (
			SELECT 1 
				FROM galutine_busena 
				WHERE paketo_id = NEW.paketo_id
			)
    THEN
        INSERT INTO galutine_busena(paketo_id, data_pristatyta, busena)
        VALUES (NEW.paketo_id, NOW(), NULL);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS paskutinis_zingsnis_ivykdytas ON zingsnis;

CREATE TRIGGER paskutinis_zingsnis_ivykdytas
AFTER UPDATE ON zingsnis
FOR EACH ROW
EXECUTE FUNCTION insertinti_galutine_besena();
